[2024-08-02T14:25:35.619+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T14:25:35.628+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-02T07:09:40.143577+00:00 [queued]>
[2024-08-02T14:25:35.634+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-02T07:09:40.143577+00:00 [queued]>
[2024-08-02T14:25:35.635+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-02T14:25:35.657+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_table_fct_user_orders> on 2024-08-02 07:09:40.143577+00:00
[2024-08-02T14:25:35.659+0700] {standard_task_runner.py:64} INFO - Started process 15151 to run task
[2024-08-02T14:25:35.662+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'copy_table_fct_user_orders', 'manual__2024-08-02T07:09:40.143577+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmp2gatai7n']
[2024-08-02T14:25:35.663+0700] {standard_task_runner.py:91} INFO - Job 132: Subtask copy_table_fct_user_orders
[2024-08-02T14:25:35.698+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-02T07:09:40.143577+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-02T14:25:35.770+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='copy_table_fct_user_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T07:09:40.143577+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T07:09:40.143577+00:00'
[2024-08-02T14:25:35.771+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T14:25:35.779+0700] {sql.py:282} INFO - Executing: 
        COPY fct_user_orders TO '/mnt/f/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        
[2024-08-02T14:25:35.782+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:25:35.797+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:25:35.827+0700] {sql.py:495} INFO - Running statement: 
        COPY fct_user_orders TO '/mnt/f/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        , parameters: None
[2024-08-02T14:25:35.829+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T14:25:35.829+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "fct_user_orders" does not exist

[2024-08-02T14:25:35.832+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=copy_table_fct_user_orders, run_id=manual__2024-08-02T07:09:40.143577+00:00, execution_date=20240802T070940, start_date=20240802T072535, end_date=20240802T072535
[2024-08-02T14:25:35.851+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 132 for task copy_table_fct_user_orders (relation "fct_user_orders" does not exist
; 15151)
[2024-08-02T14:25:35.875+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T14:25:35.883+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-02T14:25:35.890+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T14:25:35.891+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
