[2024-07-27T21:52:20.823+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-27T21:52:20.838+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_test_dag.create_table manual__2024-07-27T14:52:17.172658+00:00 [queued]>
[2024-07-27T21:52:20.843+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_test_dag.create_table manual__2024-07-27T14:52:17.172658+00:00 [queued]>
[2024-07-27T21:52:20.843+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-27T21:52:20.865+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2024-07-27 14:52:17.172658+00:00
[2024-07-27T21:52:20.867+0700] {standard_task_runner.py:64} INFO - Started process 14273 to run task
[2024-07-27T21:52:20.872+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'postgres_test_dag', 'create_table', 'manual__2024-07-27T14:52:17.172658+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/postgres_test_dag.py', '--cfg-path', '/tmp/tmpazdnwj5b']
[2024-07-27T21:52:20.872+0700] {standard_task_runner.py:91} INFO - Job 6: Subtask create_table
[2024-07-27T21:52:20.941+0700] {task_command.py:426} INFO - Running <TaskInstance: postgres_test_dag.create_table manual__2024-07-27T14:52:17.172658+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-07-27T21:52:21.022+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='postgres_test_dag' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-27T14:52:17.172658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-27T14:52:17.172658+00:00'
[2024-07-27T21:52:21.023+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-27T21:52:21.023+0700] {sql.py:282} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS test_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(50) NOT NULL
    );
    
[2024-07-27T21:52:21.027+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-07-27T21:52:21.033+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-07-27T21:54:30.866+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-27T21:54:30.868+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 438, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 560, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.144.1", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2024-07-27T21:54:30.877+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=postgres_test_dag, task_id=create_table, run_id=manual__2024-07-27T14:52:17.172658+00:00, execution_date=20240727T145217, start_date=20240727T145220, end_date=20240727T145430
[2024-07-27T21:54:30.906+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task create_table (connection to server at "192.168.144.1", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 14273)
[2024-07-27T21:54:30.915+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-27T21:54:30.926+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-07-27T21:54:30.935+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-27T21:54:30.953+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
