[2024-08-03T14:42:32.472+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T14:42:32.485+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_0 manual__2024-08-03T04:43:16.255435+00:00 [queued]>
[2024-08-03T14:42:32.495+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_0 manual__2024-08-03T04:43:16.255435+00:00 [queued]>
[2024-08-03T14:42:32.495+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-03T14:42:32.519+0700] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync_0> on 2024-08-03 04:43:16.255435+00:00
[2024-08-03T14:42:32.525+0700] {standard_task_runner.py:64} INFO - Started process 1811 to run task
[2024-08-03T14:42:32.534+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'airbyte_check_sync_0', 'manual__2024-08-03T04:43:16.255435+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpvnsx5ypm']
[2024-08-03T14:42:32.540+0700] {standard_task_runner.py:91} INFO - Job 231: Subtask airbyte_check_sync_0
[2024-08-03T14:42:32.714+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_0 manual__2024-08-03T04:43:16.255435+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T14:42:32.854+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='airbyte_check_sync_0' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T04:43:16.255435+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T04:43:16.255435+00:00'
[2024-08-03T14:42:32.856+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T14:42:32.890+0700] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-08-03T14:42:32.899+0700] {base.py:84} INFO - Using connection ID 'airflow-call-to-airbyte-example' for task execution.
[2024-08-03T14:42:32.929+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T14:42:32.933+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/sensors/airbyte.py", line 119, in execute
    super().execute(context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/sensors/airbyte.py", line 106, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job was cancelled: 
<Response [200]>
[2024-08-03T14:42:32.938+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline_supermarket_2, task_id=airbyte_check_sync_0, run_id=manual__2024-08-03T04:43:16.255435+00:00, execution_date=20240803T044316, start_date=20240803T074232, end_date=20240803T074232
[2024-08-03T14:42:32.959+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 231 for task airbyte_check_sync_0 (Job was cancelled: 
<Response [200]>; 1811)
[2024-08-03T14:42:33.001+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T14:42:33.009+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T14:42:33.025+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T14:42:33.041+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
