[2024-07-30T15:57:09.243+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-30T15:57:09.256+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_test_dag.dbt_run manual__2024-07-30T08:52:04.559517+00:00 [queued]>
[2024-07-30T15:57:09.261+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_test_dag.dbt_run manual__2024-07-30T08:52:04.559517+00:00 [queued]>
[2024-07-30T15:57:09.262+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-30T15:57:09.284+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-07-30 08:52:04.559517+00:00
[2024-07-30T15:57:09.287+0700] {standard_task_runner.py:64} INFO - Started process 40555 to run task
[2024-07-30T15:57:09.289+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_test_dag', 'dbt_run', 'manual__2024-07-30T08:52:04.559517+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dbt_test_dag.py', '--cfg-path', '/tmp/tmpr11_97_s']
[2024-07-30T15:57:09.290+0700] {standard_task_runner.py:91} INFO - Job 34: Subtask dbt_run
[2024-07-30T15:57:09.331+0700] {task_command.py:426} INFO - Running <TaskInstance: dbt_test_dag.dbt_run manual__2024-07-30T08:52:04.559517+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-07-30T15:57:09.393+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_test_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T08:52:04.559517+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-30T08:52:04.559517+00:00'
[2024-07-30T15:57:09.394+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-30T15:57:09.404+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-30T15:57:09.405+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd project/dbt_supermarket && dbt run']
[2024-07-30T15:57:09.410+0700] {subprocess.py:86} INFO - Output:
[2024-07-30T15:57:09.410+0700] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: project/dbt_supermarket: No such file or directory
[2024-07-30T15:57:09.411+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-30T15:57:09.411+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-30T15:57:09.415+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-30T15:57:09.418+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_test_dag, task_id=dbt_run, run_id=manual__2024-07-30T08:52:04.559517+00:00, execution_date=20240730T085204, start_date=20240730T085709, end_date=20240730T085709
[2024-07-30T15:57:09.441+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 34 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 40555)
[2024-07-30T15:57:09.462+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-30T15:57:09.475+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-30T15:57:09.492+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
