[2024-08-03T11:22:02.415+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T11:22:02.430+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: list_postgres_s3.copy_table_fct_user_orders manual__2024-08-03T04:21:56.037992+00:00 [queued]>
[2024-08-03T11:22:02.441+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: list_postgres_s3.copy_table_fct_user_orders manual__2024-08-03T04:21:56.037992+00:00 [queued]>
[2024-08-03T11:22:02.441+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-03T11:22:02.469+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_table_fct_user_orders> on 2024-08-03 04:21:56.037992+00:00
[2024-08-03T11:22:02.471+0700] {standard_task_runner.py:64} INFO - Started process 29543 to run task
[2024-08-03T11:22:02.474+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'list_postgres_s3', 'copy_table_fct_user_orders', 'manual__2024-08-03T04:21:56.037992+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/list_postgres_s3.py', '--cfg-path', '/tmp/tmpqlsgfcyn']
[2024-08-03T11:22:02.475+0700] {standard_task_runner.py:91} INFO - Job 207: Subtask copy_table_fct_user_orders
[2024-08-03T11:22:02.514+0700] {task_command.py:426} INFO - Running <TaskInstance: list_postgres_s3.copy_table_fct_user_orders manual__2024-08-03T04:21:56.037992+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T11:22:02.587+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='list_postgres_s3' AIRFLOW_CTX_TASK_ID='copy_table_fct_user_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T04:21:56.037992+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T04:21:56.037992+00:00'
[2024-08-03T11:22:02.588+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T11:22:02.599+0700] {sql.py:282} INFO - Executing: 
        COPY fct_user_orders TO 'F:/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        
[2024-08-03T11:22:02.603+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T11:22:02.621+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T11:22:02.657+0700] {sql.py:495} INFO - Running statement: 
        COPY fct_user_orders TO 'F:/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        , parameters: None
[2024-08-03T11:22:02.664+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T11:22:02.665+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "fct_user_orders" does not exist

[2024-08-03T11:22:02.668+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=list_postgres_s3, task_id=copy_table_fct_user_orders, run_id=manual__2024-08-03T04:21:56.037992+00:00, execution_date=20240803T042156, start_date=20240803T042202, end_date=20240803T042202
[2024-08-03T11:22:02.688+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 207 for task copy_table_fct_user_orders (relation "fct_user_orders" does not exist
; 29543)
[2024-08-03T11:22:02.727+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T11:22:02.736+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T11:22:02.745+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T11:22:02.763+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
