[2024-08-02T14:15:56.917+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-02T14:15:56.929+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.connect_supermarket_schema scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2024-08-02T14:15:56.937+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.connect_supermarket_schema scheduled__2024-08-01T00:00:00+00:00 [queued]>
[2024-08-02T14:15:56.937+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-02T14:15:56.961+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): connect_supermarket_schema> on 2024-08-01 00:00:00+00:00
[2024-08-02T14:15:56.964+0700] {standard_task_runner.py:64} INFO - Started process 12591 to run task
[2024-08-02T14:15:56.966+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'connect_supermarket_schema', 'scheduled__2024-08-01T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpen68qh45']
[2024-08-02T14:15:56.967+0700] {standard_task_runner.py:91} INFO - Job 123: Subtask connect_supermarket_schema
[2024-08-02T14:15:57.007+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.connect_supermarket_schema scheduled__2024-08-01T00:00:00+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-02T14:15:57.083+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='connect_supermarket_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-01T00:00:00+00:00'
[2024-08-02T14:15:57.084+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-02T14:15:57.093+0700] {sql.py:282} INFO - Executing: 
    SET search_path TO supermarket;
    
[2024-08-02T14:15:57.097+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:15:57.150+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-02T14:18:08.237+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-02T14:18:08.238+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 438, in run
    with self._create_autocommit_connection(autocommit) as conn:
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 560, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/postgres/hooks/postgres.py", line 175, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "192.168.1.11", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?

[2024-08-02T14:18:08.250+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=connect_supermarket_schema, run_id=scheduled__2024-08-01T00:00:00+00:00, execution_date=20240801T000000, start_date=20240802T071556, end_date=20240802T071808
[2024-08-02T14:18:08.275+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 123 for task connect_supermarket_schema (connection to server at "192.168.1.11", port 5432 failed: Connection timed out
	Is the server running on that host and accepting TCP/IP connections?
; 12591)
[2024-08-02T14:18:08.282+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-02T14:18:08.289+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-02T14:18:08.299+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-02T14:18:08.300+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
