[2024-08-03T14:42:34.638+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T14:42:34.649+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_1 manual__2024-08-03T04:43:16.255435+00:00 [queued]>
[2024-08-03T14:42:34.657+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_1 manual__2024-08-03T04:43:16.255435+00:00 [queued]>
[2024-08-03T14:42:34.657+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T14:42:34.680+0700] {taskinstance.py:2330} INFO - Executing <Task(AirbyteJobSensor): airbyte_check_sync_1> on 2024-08-03 04:43:16.255435+00:00
[2024-08-03T14:42:34.684+0700] {standard_task_runner.py:64} INFO - Started process 1822 to run task
[2024-08-03T14:42:34.685+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'airbyte_check_sync_1', 'manual__2024-08-03T04:43:16.255435+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpj24tlhcs']
[2024-08-03T14:42:34.686+0700] {standard_task_runner.py:91} INFO - Job 232: Subtask airbyte_check_sync_1
[2024-08-03T14:42:34.721+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.airbyte_check_sync_1 manual__2024-08-03T04:43:16.255435+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T14:42:34.808+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='airbyte_check_sync_1' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T04:43:16.255435+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T04:43:16.255435+00:00'
[2024-08-03T14:42:34.809+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T14:42:34.839+0700] {baseoperator.py:400} WARNING - AirbyteJobSensor.execute cannot be called outside TaskInstance!
[2024-08-03T14:42:34.848+0700] {base.py:84} INFO - Using connection ID 'airflow-call-to-airbyte-example' for task execution.
[2024-08-03T14:42:34.888+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T14:42:34.892+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/sensors/airbyte.py", line 119, in execute
    super().execute(context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 264, in execute
    raise e
  File "/usr/local/lib/python3.10/dist-packages/airflow/sensors/base.py", line 246, in execute
    poke_return = self.poke(context)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/sensors/airbyte.py", line 106, in poke
    raise AirflowException(message)
airflow.exceptions.AirflowException: Job was cancelled: 
<Response [200]>
[2024-08-03T14:42:34.900+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=airbyte_check_sync_1, run_id=manual__2024-08-03T04:43:16.255435+00:00, execution_date=20240803T044316, start_date=20240803T074234, end_date=20240803T074234
[2024-08-03T14:42:34.925+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 232 for task airbyte_check_sync_1 (Job was cancelled: 
<Response [200]>; 1822)
[2024-08-03T14:42:34.940+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T14:42:34.949+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T14:42:34.961+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T14:42:34.977+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
