[2024-08-03T10:58:43.564+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T10:58:43.574+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-03T03:55:46.320694+00:00 [queued]>
[2024-08-03T10:58:43.581+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-03T03:55:46.320694+00:00 [queued]>
[2024-08-03T10:58:43.581+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T10:58:43.605+0700] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_table_fct_user_orders> on 2024-08-03 03:55:46.320694+00:00
[2024-08-03T10:58:43.608+0700] {standard_task_runner.py:64} INFO - Started process 23251 to run task
[2024-08-03T10:58:43.610+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'copy_table_fct_user_orders', 'manual__2024-08-03T03:55:46.320694+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpxyu3wr6u']
[2024-08-03T10:58:43.612+0700] {standard_task_runner.py:91} INFO - Job 187: Subtask copy_table_fct_user_orders
[2024-08-03T10:58:43.649+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.copy_table_fct_user_orders manual__2024-08-03T03:55:46.320694+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T10:58:43.728+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='copy_table_fct_user_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T03:55:46.320694+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T03:55:46.320694+00:00'
[2024-08-03T10:58:43.729+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T10:58:43.738+0700] {sql.py:282} INFO - Executing: 
        COPY fct_user_orders TO 'F:/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        
[2024-08-03T10:58:43.742+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T10:58:43.758+0700] {base.py:84} INFO - Using connection ID 'postgres_supermarket' for task execution.
[2024-08-03T10:58:43.790+0700] {sql.py:495} INFO - Running statement: 
        COPY fct_user_orders TO 'F:/AllCode/Data Engineer/fct_user_orders.csv' CSV HEADER;
        , parameters: None
[2024-08-03T10:58:43.796+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T10:58:43.797+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/operators/sql.py", line 288, in execute
    output = hook.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 442, in run
    self._run_command(cur, sql_statement, parameters)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/common/sql/hooks/sql.py", line 500, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "fct_user_orders" does not exist

[2024-08-03T10:58:43.801+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=copy_table_fct_user_orders, run_id=manual__2024-08-03T03:55:46.320694+00:00, execution_date=20240803T035546, start_date=20240803T035843, end_date=20240803T035843
[2024-08-03T10:58:43.826+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 187 for task copy_table_fct_user_orders (relation "fct_user_orders" does not exist
; 23251)
[2024-08-03T10:58:43.864+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T10:58:43.872+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T10:58:43.880+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T10:58:43.881+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
