[2024-08-03T10:49:58.443+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-03T10:49:58.453+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_trigger_sync_2 manual__2024-08-03T03:49:50.152465+00:00 [queued]>
[2024-08-03T10:49:58.457+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_supermarket_2.airbyte_trigger_sync_2 manual__2024-08-03T03:49:50.152465+00:00 [queued]>
[2024-08-03T10:49:58.458+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-03T10:49:58.480+0700] {taskinstance.py:2330} INFO - Executing <Task(AirbyteTriggerSyncOperator): airbyte_trigger_sync_2> on 2024-08-03 03:49:50.152465+00:00
[2024-08-03T10:49:58.483+0700] {standard_task_runner.py:64} INFO - Started process 20429 to run task
[2024-08-03T10:49:58.485+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_supermarket_2', 'airbyte_trigger_sync_2', 'manual__2024-08-03T03:49:50.152465+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_supermarket_2.py', '--cfg-path', '/tmp/tmpnp0lwp8u']
[2024-08-03T10:49:58.486+0700] {standard_task_runner.py:91} INFO - Job 171: Subtask airbyte_trigger_sync_2
[2024-08-03T10:49:58.522+0700] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_supermarket_2.airbyte_trigger_sync_2 manual__2024-08-03T03:49:50.152465+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-08-03T10:49:58.599+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_supermarket_2' AIRFLOW_CTX_TASK_ID='airbyte_trigger_sync_2' AIRFLOW_CTX_EXECUTION_DATE='2024-08-03T03:49:50.152465+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-03T03:49:50.152465+00:00'
[2024-08-03T10:49:58.599+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-03T10:49:58.613+0700] {base.py:84} INFO - Using connection ID 'airflow-call-to-airbyte-example' for task execution.
[2024-08-03T10:49:58.627+0700] {http.py:200} ERROR - HTTP error: Not Found
[2024-08-03T10:49:58.627+0700] {http.py:201} ERROR - {"message":"Internal Server Error: Could not find configuration for STANDARD_SYNC: de559778-aa2a-419a-86b4-0b96c085c8e0.","exceptionClassName":"io.airbyte.commons.server.errors.IdNotFoundKnownException","exceptionStack":["io.airbyte.commons.server.errors.IdNotFoundKnownException: Could not find configuration for STANDARD_SYNC: de559778-aa2a-419a-86b4-0b96c085c8e0.","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:32)","\tat io.airbyte.server.apis.ConnectionApiController.syncConnection(ConnectionApiController.java:261)","\tat io.airbyte.server.apis.$ConnectionApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)","\tat io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4325)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)","\tat io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)","\tat io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)","\tat io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)","\tat io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)","\tat io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1583)","Caused by: io.airbyte.config.persistence.ConfigNotFoundException: config type: STANDARD_SYNC id: de559778-aa2a-419a-86b4-0b96c085c8e0","\tat io.airbyte.config.persistence.ConfigRepository.getStandardSync(ConfigRepository.java:988)","\tat io.airbyte.commons.server.handlers.SchedulerHandler.submitManualSyncToWorker(SchedulerHandler.java:798)","\tat io.airbyte.commons.server.handlers.SchedulerHandler.syncConnection(SchedulerHandler.java:602)","\tat io.airbyte.server.apis.ConnectionApiController.lambda$syncConnection$18(ConnectionApiController.java:261)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)","\t... 13 more"],"rootCauseExceptionClassName":"java.lang.Class","rootCauseExceptionStack":["io.airbyte.config.persistence.ConfigNotFoundException: config type: STANDARD_SYNC id: de559778-aa2a-419a-86b4-0b96c085c8e0","\tat io.airbyte.config.persistence.ConfigRepository.getStandardSync(ConfigRepository.java:988)","\tat io.airbyte.commons.server.handlers.SchedulerHandler.submitManualSyncToWorker(SchedulerHandler.java:798)","\tat io.airbyte.commons.server.handlers.SchedulerHandler.syncConnection(SchedulerHandler.java:602)","\tat io.airbyte.server.apis.ConnectionApiController.lambda$syncConnection$18(ConnectionApiController.java:261)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:28)","\tat io.airbyte.server.apis.ConnectionApiController.syncConnection(ConnectionApiController.java:261)","\tat io.airbyte.server.apis.$ConnectionApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invokeUnsafe(AbstractExecutableMethodsDefinition.java:461)","\tat io.micronaut.context.DefaultBeanContext$BeanContextUnsafeExecutionHandle.invokeUnsafe(DefaultBeanContext.java:4325)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:271)","\tat io.micronaut.web.router.DefaultUriRouteMatch.execute(DefaultUriRouteMatch.java:39)","\tat io.micronaut.http.server.RouteExecutor.executeRouteAndConvertBody(RouteExecutor.java:490)","\tat io.micronaut.http.server.RouteExecutor.lambda$callRoute$6(RouteExecutor.java:467)","\tat io.micronaut.core.execution.ExecutionFlow.lambda$async$1(ExecutionFlow.java:87)","\tat io.micronaut.core.propagation.PropagatedContext.lambda$wrap$3(PropagatedContext.java:211)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1583)"]}
[2024-08-03T10:49:58.627+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-03T10:49:58.630+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/http/hooks/http.py", line 198, in check_response
    response.raise_for_status()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://localhost:8000/api/v1/connections/sync

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/operators/airbyte.py", line 86, in execute
    job_object = hook.submit_sync_connection(connection_id=self.connection_id)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/airbyte/hooks/airbyte.py", line 185, in submit_sync_connection
    return self.run(
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/http/hooks/http.py", line 188, in run
    return self.run_and_check(session, prepped_request, extra_options)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/http/hooks/http.py", line 239, in run_and_check
    self.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/http/hooks/http.py", line 202, in check_response
    raise AirflowException(str(response.status_code) + ":" + response.reason)
airflow.exceptions.AirflowException: 404:Not Found
[2024-08-03T10:49:58.633+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_supermarket_2, task_id=airbyte_trigger_sync_2, run_id=manual__2024-08-03T03:49:50.152465+00:00, execution_date=20240803T034950, start_date=20240803T034958, end_date=20240803T034958
[2024-08-03T10:49:58.653+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 171 for task airbyte_trigger_sync_2 (404:Not Found; 20429)
[2024-08-03T10:49:58.657+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-03T10:49:58.667+0700] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-08-03T10:49:58.679+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-03T10:49:58.680+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
