[2024-07-29T15:57:56.658+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-29T15:57:56.675+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_test_dag.dbt_run manual__2024-07-29T08:52:50.742655+00:00 [queued]>
[2024-07-29T15:57:56.683+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_test_dag.dbt_run manual__2024-07-29T08:52:50.742655+00:00 [queued]>
[2024-07-29T15:57:56.683+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-29T15:57:56.708+0700] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-07-29 08:52:50.742655+00:00
[2024-07-29T15:57:56.710+0700] {standard_task_runner.py:64} INFO - Started process 65774 to run task
[2024-07-29T15:57:56.716+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_test_dag', 'dbt_run', 'manual__2024-07-29T08:52:50.742655+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dbt_test_dag.py', '--cfg-path', '/tmp/tmpahi2dglp']
[2024-07-29T15:57:56.719+0700] {standard_task_runner.py:91} INFO - Job 29: Subtask dbt_run
[2024-07-29T15:57:56.757+0700] {task_command.py:426} INFO - Running <TaskInstance: dbt_test_dag.dbt_run manual__2024-07-29T08:52:50.742655+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-07-29T15:57:56.812+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_test_dag' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T08:52:50.742655+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-29T08:52:50.742655+00:00'
[2024-07-29T15:57:56.812+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-29T15:57:56.822+0700] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-29T15:57:56.823+0700] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd dbt_supermarket && dbt run']
[2024-07-29T15:57:56.830+0700] {subprocess.py:86} INFO - Output:
[2024-07-29T15:57:56.831+0700] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: dbt_supermarket: No such file or directory
[2024-07-29T15:57:56.831+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-07-29T15:57:56.831+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-29T15:57:56.836+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-07-29T15:57:56.838+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_test_dag, task_id=dbt_run, run_id=manual__2024-07-29T08:52:50.742655+00:00, execution_date=20240729T085250, start_date=20240729T085756, end_date=20240729T085756
[2024-07-29T15:57:56.858+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 65774)
[2024-07-29T15:57:56.886+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-29T15:57:56.899+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-29T15:57:56.915+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
