[2024-07-31T10:59:31.461+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-31T10:59:31.480+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_subprocess_test.dbt_run scheduled__2024-07-30T00:00:00+00:00 [queued]>
[2024-07-31T10:59:31.489+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_subprocess_test.dbt_run scheduled__2024-07-30T00:00:00+00:00 [queued]>
[2024-07-31T10:59:31.489+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-31T10:59:31.513+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): dbt_run> on 2024-07-30 00:00:00+00:00
[2024-07-31T10:59:31.517+0700] {standard_task_runner.py:64} INFO - Started process 13613 to run task
[2024-07-31T10:59:31.521+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'dbt_subprocess_test', 'dbt_run', 'scheduled__2024-07-30T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dbt_subprocess_test.py', '--cfg-path', '/tmp/tmpj_u079fd']
[2024-07-31T10:59:31.523+0700] {standard_task_runner.py:91} INFO - Job 47: Subtask dbt_run
[2024-07-31T10:59:31.570+0700] {task_command.py:426} INFO - Running <TaskInstance: dbt_subprocess_test.dbt_run scheduled__2024-07-30T00:00:00+00:00 [running]> on host DESKTOP-RHVHV7A.
[2024-07-31T10:59:31.634+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dbt_subprocess_test' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-30T00:00:00+00:00'
[2024-07-31T10:59:31.635+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-31T10:59:31.645+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-31T10:59:31.646+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/root/airflow/dags/dbt_subprocess_test.py", line 26, in run_dbt_command
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Admin/dbt_supermarket'
[2024-07-31T10:59:31.650+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dbt_subprocess_test, task_id=dbt_run, run_id=scheduled__2024-07-30T00:00:00+00:00, execution_date=20240730T000000, start_date=20240731T035931, end_date=20240731T035931
[2024-07-31T10:59:31.665+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 47 for task dbt_run ([Errno 2] No such file or directory: 'C:/Users/Admin/dbt_supermarket'; 13613)
[2024-07-31T10:59:31.694+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-31T10:59:31.708+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-31T10:59:31.717+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
